//
// Created by D Rimron-Soutter on 3/11/2020.
//
#ifndef D3_BUILD_H
#define D3_BUILD_H

// Autogenerated on Tue Dec 29 16:26:57 GMT 2020
#define D3_BUILD       "63"
#define D3_VER	       "0.5.b"

#endif //D3_BUILD_H
