//
// Created by D Rimron-Soutter on 3/11/2020.
//
#ifndef D3_BUILD_H
#define D3_BUILD_H

// Autogenerated on Wed Nov 18 22:40:51 GMT 2020
#define D3_BUILD       "36"
#define D3_VER	       "0.4.2"

#endif //D3_BUILD_H
