//
// Created by D Rimron-Soutter on 3/11/2020.
//
#ifndef D3_BUILD_H
#define D3_BUILD_H

// Autogenerated on Thu Nov  5 21:27:37 GMT 2020
#define D3_BUILD       "14"
#define D3_VER	       "0.2.1"

#endif //D3_BUILD_H
